##############################################
#     Make file of mt9v113 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/mt9v113
EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HIK3_CAMERA_MT9V113) += mt9v113.o
#obj-m += mt9v113.o

#################### END #####################
