/* This file is auto-generated by tool, DO NOT modify it manully. */

#ifndef CONFIG_BOARDIDS_H
#define CONFIG_BOARDIDS_H

#define BOARD_ID_S10   128
#define BOARD_ID_LINK_S10   130
#define BOARD_ID_CS_S10   129
#define BOARD_ID_U9510   119
#define BOARD_ID_VACS_K3OEM   1
#define BOARD_ID_CS_U9510   103
#define BOARD_ID_K3OEM   0
#define BOARD_ID_VCCS_K3OEM   16

#endif
